import '@/Styles/globals.css'
import NavMenu from "@/Components/NavMenu";
import React from "react";
import AuthProvider from "@/app/AuthProvider";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <AuthProvider>
      <html lang="en">
        <body>
          <NavMenu />
          {children}
        </body>
      </html>
      </AuthProvider>
  )
}